import { MediaItem } from '@rntp/player';


export const playListData: MediaItem[] = [
  {
    mediaId: "1",
    title: "Sang-e-Mah OST",
    artist: "Atif Aslam",
    albumTitle: "HUM Drama OST",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlXxJ4jF-PUqLRzr9Vo3b1bxybbNVCSV-zi6bI7T6zXfjw-wS3xkIKTy4nTGQZWD-cDySEZA&s=10",
    url: require("./assets/Audios/Sang-e-Mah.m4a"),
  },
  {
    mediaId: "2",
    title: "Mann Mayal OST",
    artist: "Qurat-ul-Ain Baloch",
    albumTitle: "HUM Drama OST",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBfbA7e5l8C38qNEWuVcQT6eD_BsoOIU-VYRxaQ6Llk8otQ68gTzkFktiV_yRjw2BX6eu9&s=10",
    url: require("./assets/Audios/Mann-Mayal_OST.m4a"),
  },
  {
    mediaId: "3",
    title: "Mahiya Tere Wekhn Nu",
    artist: "Fareed Ayaz & Abu Muhammad",
    albumTitle: "Qawali",
    artworkUrl: "https://i.ytimg.com/vi/zE75Kbg_zpU/maxresdefault.jpg",
    url: require("./assets/Audios/Mahiya-Tere.m4a"),
  },
  {
    mediaId: "4",
    title: "Man Atkya Be-Parwah de Nal",
    artist: "Ustad Nusrat Fateh Ali Khan",
    albumTitle: "Prem Deewani",
    artworkUrl: "https://i.ytimg.com/vi/iBNy6HJBIsk/maxresdefault.jpg",
    url: require("./assets/Audios/Man_Atkya.m4a"),
  },
  {
    mediaId: "5",
    title: "Matt Jao",
    artist: "Muhammad Faiz",
    albumTitle: "Desi Melodies",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnMUwV7GfwLNgylpGXFlrN3cRdw6VVoaOhJS9N2e7Nig&s=10",
    url: require("./assets/Audios/Matt_Jao.m4a"),
  },
  {
    mediaId: "6",
    title: "Paar Channa De",
    artist: "Shilpa Rao & Noori",
    albumTitle: "Coke Studio Season 9",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE519rHEmxlaw_81GnYDPx2erU1Zk7-unnhlspzbRM_Q&s=10",
    url: require("./assets/Audios/Paar_Channa_De.m4a"),
  },
  {
    mediaId: "7",
    title: "Piya Ghar Aya By NFAK",
    artist: "Ustad Nusrat Fateh Ali Khan",
    albumTitle: "DorChester Hotel UK",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGd9i4Oxcgt28hXxuswsVB66kePQ_O6h7D7J9NKORPjQ&s=10",
    url: require("./assets/Audios/Piya_ghar_Aya_By_NFAK.m4a"),
  },
  {
    mediaId: "8",
    title: "Piya Ghar Aya Remix",
    artist: "Ustad Nusrat Fateh Ali Khan",
    albumTitle: "NFAK Remix",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlG0PYeNbwKrlPXvf2EKBSyyWrUzyhdESP4mqi7HWogg&s=10",
    url: require("./assets/Audios/Piya_ghar_aya_Remix.m4a"),
  },
  {
    mediaId: "9",
    title: "Piya Ghar Aya",
    artist: "Fareed Ayaz & Abu Muhammad",
    albumTitle: "Coke Studio Season 11",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAOSuuXM83S4EtOqy6FYguH9YHby8Nt61Y-QvaHB2yWQ&s=10",
    url: require("./assets/Audios/Piya_ghar_aya.m4a"),
  },
  {
    mediaId: "10",
    title: "Tera Wo Pyar",
    artist: "Asim Azhar & Momina Mustehsan",
    albumTitle: "Coke Studio Season 9",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnfCtjM4Su4S_FL3s9H499ZKRZEzzIngqckN3UDRCKvQ&s=10",
    url: require("./assets/Audios/Tera_Wo_Pyar.m4a"),
  },

  {
    mediaId: "11",
    title: "Tajdar-e-Haram",
    artist: "Atif Aslam",
    albumTitle: "Coke Studio Season 8",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKDDukHC8iQZHXWZKeinu_GLDH3Z8QjBikood7fc2xtA&s=10",
    url: require("./assets/Audios/Tajdar-e-Haram.m4a"),
  },

  {
    mediaId: "12",
    title: "Afreen Afreen",
    artist: "Rahat Fateh Ali & Momina Mustehsan",
    albumTitle: "Coke Studio Season 9",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvoac12kW97DFpFtRIl6cxZ3NDjXwj9ONbWILoUpuunQ&s=10",
    url: require("./assets/Audios/Afreen_Afreen.m4a"),
  },

  {
    mediaId: "13",
    title: "Charkha",
    artist: "Fareed Ayaz & Abu Muhammad",
    albumTitle: "Mehfil-e-Sama",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYYz0O5JoLHN_pUcJ3IV4hjBafOQXAo7-1G1-2mqiW9w&s=10",
    url: require("./assets/Audios/Charkha.m4a"),
  },
  {
    mediaId: "14",
    title: "Charka By NFAK",
    artist: "Ustad Nusrat Fateh Ali Khan",
    albumTitle: "Unpredictable",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1fglyb99S4HnI5N0l0qfzSZWT31Z70V-4jsz_K9Mm0w&s=10",
    url: require("./assets/Audios/Charka_By_Nusrat.m4a"),
  },
  {
    mediaId: "15",
    title: "Chaap Tilak",
    artist: "Hadiqa Qayani",
    albumTitle: "Wajd",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCKkYET9JBtSo3avfqCKKM1rCFbXBafKtGLMM1ziatBg&s=10",
    url: require("./assets/Audios/Chaap_Tilak.m4a"),
  },
  {
    mediaId:"31",
    title:'52_Bars(Karan_Aujla)' ,
    artist:'Karan Aujla & Ikky',
    albumTitle:'For You' ,
    artworkUrl:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdYrq7GU6sFKigVjFd8ACTY1lPzySgGcKrR1iEYGIoYQ&s=10',
    url:require('./assets/Audios/52_Bars.m4a')
    },
  // ... continue same pattern
    {
    mediaId: "32",
    title: "ADMIRIN YOU",
    artist: "Karan Aujla & Ikky",
    albumTitle: "Making Memories",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAM7oRLTJe-2BOegiflNc8ylvYVloJ3es1o1gGIfwWyw&s=10",
    url: require("./assets/Audios/Admirin_You.m4a"),
    },
    {
    mediaId: "33",
    title: "Afusic Pal Pal",
    artist: "Afusic, Ali Somroo",
    albumTitle: "Pal Pal",
    artworkUrl: "https://images.unsplash.com/photo-1628015893843-5f7f6f6ccb01?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjZ8fGNpbmVtYXRpY3xlbnwwfHwwfHx8MA%3D%3D",
    url: require("./assets/Audios/Afusic_Pal_Pal.m4a"),
    },
    {
    mediaId: "34",
    title: "Agar Ho Tum",
    artist: "Tanish Bagchi, Kausar Munir & Jaubin Nautiyal",
    albumTitle: "Aj di dehari rakh",
    artworkUrl: "https://images.unsplash.com/photo-1647505384832-9a8abd5dd56f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fGNpbmVtYXRpY3xlbnwwfHwwfHx8MA%3D%3D",
    url: require("./assets/Audios/Agar_Ho_Tum.m4a"),
    },
    {
    mediaId: "35",
    title: "Akhiyan Milavanga",
    artist: "Arijit Singh & Sruthy Sasidharan",
    albumTitle: "Commando 3",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFH8ogfqO7wOG0KIQ_OIWZwfriIn-XnCrm4RiSeahzEg&s=10",
    url: require("./assets/Audios/Akhiyan_Milavan_Ga.m4a"),
    },
    {
    mediaId: "36",
    title: "Arz Kiya Hy",
    artist: "Anuv Jain",
    albumTitle: "Coke Studio India",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxxuN5THkgTOVt8stHm95VgHDSj33cGa0shKz5bRDziA&s",
    url: require("./assets/Audios/Arz_Kiya_hy.m4a"),
    },
    {
    mediaId: "37",
    title: "AT PEACE",
    artist: "Karan Aujla & Ikky",
    albumTitle: "At Peace",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7W9-4u_o_Gs4wzwhaZqLCL8j-xWh9FEuXdhjKc29ESw&s=10",
    url: require("./assets/Audios/At_Peace.m4a"),
    },
    {
    mediaId: "38",
    title: "BOYFRIEND",
    artist: "Karan Aujla & Ikky",
    albumTitle: "P-POP Culture",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2gq5Zq_tPPJPxWXMZJAMCIT_9DhoETDpqSwa0DK8NCw&s=10",
    url: require("./assets/Audios/boyfriend.m4a"),
    },
    {
    mediaId: "39",
    title: "Bullya",
    artist: "Pritam & Arijit Singh",
    albumTitle: "Aye Dil Hy Mushkil",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4krNm7Svl4z4bv7HJqPB2PDQ-9BQDXyZ4Av7M09HlfA&s=10",
    url: require("./assets/Audios/Bullya.m4a"),
    },
    {
    mediaId: "40",
    title: "C WALK",
    artist: "Karan Aujla & Ikky",
    albumTitle: "Karan Aujla(Topic)",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIOsKSHfXZujGu8j33HHGx6pos_jOEwn2r5WsMJhza-w&s=10",
    url: require("./assets/Audios/C_Walk.m4a"),
    },
    {
    mediaId: "41",
    title: "Chal Diye Tum Kahan",
    artist: "Unknown",
    albumTitle: "Pakistani Drama OST",
    artworkUrl: "https://images.unsplash.com/photo-1579024608779-8eadd0f595b0?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGNpbmVtYXRpY3xlbnwwfHwwfHx8MA%3D%3D",
    url: require("./assets/Audios/Chal_diye_tm_kahan.m4a"),
    },
    {
    mediaId: "42",
    title: "Channa Mereya",
    artist: "Arijit Singh & Unknown",
    albumTitle: "Sony Music India",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUJZY6egvLtCh2X7pjU3zQgcGwBNX4hRj6D8aaACPa7w&s=10",
    url: require("./assets/Audios/Channa_Mereya.m4a"),
    },
    {
    mediaId: "43",
    title: "DAYTONNA",
    artist: "Karan Aujla & Ikky",
    albumTitle: "P-POP Culture",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaF4GqBTIVUmyzMAM8dPmDisH8IhTWuaGMUVGTK6swow&s=10",
    url: require("./assets/Audios/Daytonna.m4a"),
    },
    {
    mediaId: "44",
    title: "Dekha Tenu",
    artist: "Jaani & Muhammad Faiz",
    albumTitle: "BollyWood Movie",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-ebmfMzDW-VpwHQU73NGtMTQna6afZCGnf6dzWMA-gA&s=10",
    url: require("./assets/Audios/Dekha_tenu.m4a"),
    },
    {
    mediaId: "45",
    title: "Faaslay",
    artist: "Kaavish",
    albumTitle: "Kaavish",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAYgR-19kqiLDsv2lGgqPLRy55xQfsrYO4DzhnTFknKA&s=10",
    url: require("./assets/Audios/Faaslay.m4a"),
    },
    {
    mediaId: "46",
    title: "FOR A REASON",
    artist: "Karan Aujla & Ikky",
    albumTitle: "P-POP Culture",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrBDMVqpFLrQXObvbA97CsbcBmACGgc3pz53SQMbS8RQ&s=10",
    url: require("./assets/Audios/For_A_Reason.m4a"),
    },
    {
    mediaId: "47",
    title: "GHAR NAARI",
    artist: "Fareed Ayaz & Abu Muhammad",
    albumTitle: "ARY FILMS",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRygm8hhliFu6R3y1SrSbAjKpGmWj8Y1Mh4_4S_Xy-FFg&s=10",
    url: require("./assets/Audios/Ghar_Naari.m4a"),
    },
    {
    mediaId: "48",
    title: "Heeriye Heeriye",
    artist: "Arijit Singh & Shreya Ghoshal",
    albumTitle: "Happy Hardy And Heer",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQgmqrFpiC7vNr2cM2HeGj1ABc8Wa0U0cofaRVgTVubw&s=10",
    url: require("./assets/Audios/Heeriye.m4a"),
    },
    {
    mediaId: "49",
    title: "Ishq Murshid OST",
    artist: "Ahmad Jahazaib",
    albumTitle: "HUM Drama OST",
    artworkUrl: "https://images.unsplash.com/photo-1652201837148-edf8032ae8c1?q=80&w=736&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    url: require("./assets/Audios/Ishq_murshid_OST.m4a"),
    },
    {
    mediaId: "50",
    title: "Ishqa Ve",
    artist: "Zeeshan Ali",
    albumTitle: "Ishqa Ve",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2Y_tor1JuFfEMUH1gXHL1X4h0-u6PNR7KZN9OOQCW_w&s=10",
    url: require("./assets/Audios/Ishqa_ve.m4a"),
    },
    {
    mediaId: "51",
    title: "Jayie Sajna",
    artist: "Jasmine Sandlas & Satinder Sartaaj",
    albumTitle: "Dhurandhar 2",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8GK8kD-orqIi-q0yIAsHxI3XXA5_U36pUQKyx_Gjbmw&s=10",
    url: require("./assets/Audios/Jayie_Sajna.m4a"),
    },
    {
    mediaId: "52",
    title: "JUDGE",
    artist: "Amrindar Gill",
    albumTitle: "Chal Mera Putt 3",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjxfbaYvC6UuyVookgIfLgFOIXqrC_fruCkcwM1_dokw&s=10",
    url: require("./assets/Audios/Judge.m4a"),
    },
    {
    mediaId: "53",
    title: "Jo Tum Mere Ho",
    artist: "Anuv Jain",
    albumTitle: "Anuv Jain",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEPLi5bLph9p68AuxRe6FAJ_wbYnqwCuC5I8t35zAsEA&s",
    url: require("./assets/Audios/Jo_Tum_Mere_Ho.m4a"),
    },
    {
    mediaId: "54",
    title: "Jo tu Na Mila",
    artist: "Asim Azhar",
    albumTitle: "Jo Tu Na Mila",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwAlaDNvZKPwNG5BTIPmqGzU47zMn2oozyQNIrvRF4_Q&s=10",
    url: require("./assets/Audios/Jo_Tu_Na_Mila.m4a"),
    },
    {
    mediaId: "55",
    title: "Jutti Kasoori",
    artist: "Unknown",
    albumTitle: "Suno Sur Taal",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJOJi879UNFxp0hNcZuA-QaK7F_uBIfIzpFGr1C8Dvrw&s=10",
    url: require("./assets/Audios/jutti_kasoori.m4a"),
    },
    {
    mediaId: "56",
    title: "Kahani Suno",
    artist: "Kaifi Khalil",
    albumTitle: "Mujhe Pyar Hua Tha",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_pJUvpjNFYe-jiTa06HEa74pfNzzKRlJsSvvYrBeSmA&s",
    url: require("./assets/Audios/Kahani_Suno.m4a"),
    },
    {
    mediaId: "57",
    title: "Jad Mil Ke Betha Gy",
    artist: "Amrindar Gill",
    albumTitle: "Angraiz Movie",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP8lZrEdv15Mw3_O9ienjjsqJzU5ACtIpKfsUIrcKUAg&s=10",
    url: require("./assets/Audios/jd_mil_k_betha.m4a"),
    },
    {
    mediaId: "58",
    title: "ON TOP",
    artist: "Karan Aujla & Ikky",
    albumTitle: "ON TOP",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRy_sCeF2HdcRpHFwK3uhaOclsMvnZnkpcNmynMt5x1PQ&s=10",
    url: require("./assets/Audios/ON_TOP.m4a"),
    },
    {
    mediaId: "59",
    title: "Zindagi Haseen",
    artist: "Unknown",
    albumTitle: "Zindagi Haseen",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTF3PRrrjoHnbjnXCsGwLKvmTSCdL6ah8XUlIeokGBvrQ&s=10",
    url: require("./assets/Audios/Zindagi_Tere_Naal.m4a"),
    },
    {
    mediaId: "60",
    title: "Raanjhan",
    artist: "Sachet-Parampara",
    albumTitle: "Raanjhan",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbYZih9ErYI7NXk7S22tFPpDhVqUhsXg1rTu59y0BO_g&s=10",
    url: require("./assets/Audios/Raanjhan.m4a"),
    },
    {
    mediaId: "61",
    title: "Rafta Rafta",
    artist: "Atif Aslam",
    albumTitle: "Rafta Rafta",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlZpyUyKwl-pFfHX78JAr5ctd0o49EXM_FMfBf_5nwag&s=10",
    url: require("./assets/Audios/Rafta_rafta.m4a"),
    },
    {
    mediaId: "62",
    title: "Ranjhya We",
    artist: "Zain Zohaib",
    albumTitle: "Ranjhya We",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQv56-qBSo8X4BKKU5M8pqzW5VCz8qbkztZ48OLqaj2HQ&s=10",
    url: require("./assets/Audios/Ranjhya_ve.m4a"),
    },
    {
    mediaId: "63",
    title: "Raavi",
    artist: "Sajid Ali",
    albumTitle: "Raavi",
    artworkUrl: "https://plus.unsplash.com/premium_photo-1710961232986-36cead00da3c?q=80&w=784&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    url: require("./assets/Audios/Ravi.m4a"),
    },
    {
    mediaId: "64",
    title: "Aj Di Dehari Rakh",
    artist: "Yousuf Salli",
    albumTitle: "Aj di dehari rakh",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5LyRUY--ZWw6pL_AnaapKuLD35IvAM5oaur3gY3C70w&s=10",
    url: require("./assets/Audios/Aj_Di_Dehari_Rakh.m4a"),
    },
    {
    mediaId: "65",
    title: "Sajdaa",
    artist: "Rahat Fateh Ali Khan & Others",
    albumTitle: "Sajdaa",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiDpny3236kaVGN5FURa2tltRyWbVNo46iCCTrUwQ6jw&s=10",
    url: require("./assets/Audios/Sajda.m4a"),
    },
    {
    mediaId: "66",
    title: "SOFTLY",
    artist: "Karan Aujla & Ikky",
    albumTitle: "SOFTLY",
    artworkUrl: "https://images.unsplash.com/photo-1633885274964-d5a5d914bcb3?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    url: require("./assets/Audios/Softly.m4a"),
    },
    {
    mediaId: "67",
    title: "Sukoon 2.0",
    artist: "Sajid-Suleman & Arijit Singh",
    albumTitle: "Sukoon 2.0",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVzIWZK-SUENGrs4AtK-rSfdEqV815bMJTJwnTgozWlA&s=10",
    url: require("./assets/Audios/Sukoon.m4a"),
    },
    {
    mediaId: "68",
    title: "Tose Naina",
    artist: "Shilpa Rao & Unknown",
    albumTitle: "Tose Naina",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg1LL1lq0VZFW1XAWXuAUq5cCrZQNKovVQV6rqM1ZzEw&s=10",
    url: require("./assets/Audios/Tose_naina.m4a"),
    },
    {
    mediaId: "69",
    title: "Tu Jhoom",
    artist: "Abida Parveen & Naseebo Lal",
    albumTitle: "Jhoom",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbud7ngmRaFOOKpdF1o3Q1Y3rYXoCkK9jqVyPEfKrVRA&s=10",
    url: require("./assets/Audios/TU_Jhoom.m4a"),
    },
    {
    mediaId: "70",
    title: "Ve Kamlya",
    artist: "Arijit Singh",
    albumTitle: "Ve Kamlya",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQgmqrFpiC7vNr2cM2HeGj1ABc8Wa0U0cofaRVgTVubw&s=10",
    url: require("./assets/Audios/ve_kamlya.m4a"),
    },
    {
    mediaId: "71",
    title: "WAVY",
    artist: "Karan Aujla & Ikky",
    albumTitle: "WAVY",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsEPFTluu432bc3JOcm-8l1dbOrXwROmUWn9eY_J2c9Q&s=10",
    url: require("./assets/Audios/WAVY.m4a"),
    },
    {
    mediaId: "72",
    title: "Russian Song(Motherland)",
    artist: "Tatyana Kurtukova",
    albumTitle: "Motherland",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcW7TzqJFLWmzfVjk2mRaktgTZdOg6flY9ua0CCMkWMQ&s=10",
    url: require("./assets/Audios/RussianSong.m4a"),
    },
    {
    mediaId: "73",
    title: "Winning Speech",
    artist: "Karan Aujla & Ikky",
    albumTitle: "Winning Speech",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReJQcfC07a-58g7KG6CyWCVFw664aENcuIYipz-Z-nYQ&s=10",
    url: require("./assets/Audios/Winning_speech.m4a"),
    },
    {
    mediaId: "74",
    title: "Shakira,Burna Boy - Dai Dai",
    artist: "Shakira & Burna Boy",
    albumTitle: "Dai Dai",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxPLzgH8jSMi_QsjRBnvczsystAjPnw4ZcVHPdg6OK-A&s=10",
    url: require("./assets/Audios/Winning_speech.m4a"),
    },
    {
    mediaId: "75",
    title: "Bachke Bachke",
    artist: "Karan Aujla & Ikky",
    albumTitle: "Bachke Bachke",
    artworkUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFSGdnKWDfHW1RSxroCD8IvhD_OckLuFsR-LOEfMVShg&s=10",
    url: require("./assets/Audios/bachke.m4a"),
    }

];